--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cooldogedev/libBook
build-by-default: true
branches:
- main
projects:
  libBook:
    path: ""
    model: virion
    type: library
...

